function filter_generatehdl(filtobj)
%  FILTER_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
%  Generated on: 2022-05-24 15:47:05
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  TargetLanguage: VHDL
%  TargetDirectory: C:\Users\dudekpob\Desktop\Projekty\ACC\filtry
%  TestBenchStimulus: impulse step ramp chirp noise 
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Filter (real)
%  -------------------------------
%  Filter Structure  : Direct-Form FIR
%  Filter Length     : 51
%  Stable            : Yes
%  Linear Phase      : Yes (Type 1)

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'TargetLanguage', 'VHDL',... 
               'TargetDirectory', 'C:\Users\dudekpob\Desktop\Projekty\ACC\filtry',... 
               'TestBenchStimulus',  {'impulse', 'step', 'ramp', 'chirp', 'noise'},... 
               'GenerateHDLTestbench', 'on');

% [EOF]
